from odoo import fields, models


class ProjectProject(models.Model):
    _inherit = "project.project"

    dropship_picking_count = fields.Integer(
        related="sale_order_id.dropship_picking_count",
        string="Dropship Picking Count",
    )

    def action_view_dropship(self):
        return self.sale_order_id.action_view_dropship()

    def action_view_purchase_orders(self):
        return self.sale_order_id.action_view_purchase_orders()

    def _get_stat_buttons(self):
        buttons = super()._get_stat_buttons()
        sale_order = self.sudo().sale_order_id
        if self.env.user.has_group('stock.group_stock_user'):
            buttons.append({
                'icon': 'truck',
                'text': self.env._('Dropshipping'),
                'number': sale_order.dropship_picking_count,
                'action_type': 'object',
                'action': 'action_view_dropship',
                'show': sale_order.dropship_picking_count > 0,
                'sequence': 2,
            })
        if self.env.user.has_group('purchase.group_purchase_user'):
            # Odoo 18 core (project_purchase) already provides a "Purchase Orders"
            # button counting the POs linked to the project. This one counts the POs
            # generated by the project's sales order: different icon, label and
            # sequence to avoid any confusion between the two.
            buttons.append({
                'icon': 'shopping-cart',
                'text': self.env._('Purchases from SO'),
                'number': sale_order.purchase_order_count,
                'action_type': 'object',
                'action': 'action_view_purchase_orders',
                'show': sale_order.purchase_order_count > 0,
                'sequence': 37,
            })
        return buttons
